title: "LunarNet.space"
description: "Roaming The Stars"
url: https://lunarnet.space # no trailing slash
logo: https://github.com/lunarki.png?w=256

permalink: /post/:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: css
  style: compressed

compress_html:
  clippings: all
  comments: all
  blanklines: false
